from dataclasses import dataclass, field
from typing import Optional


@dataclass
class PageNode:
    title: str
    content: str        # raw text, populated at leaves
    summary: str        # generated by LLM, populated by indexer
    depth: int          # 0 = root, 1 = section, 2 = subsection
    children: list = field(default_factory=list)
    parent: Optional["PageNode"] = None

    def is_leaf(self) -> bool:
        return len(self.children) == 0
